title: Roberto Busby # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br>
👋 Hi, I'm a Data Analyst with experience in data manipulation, business intelligence, and process automation. I love turning complex data into insights that drive positive change.
<br><br>
<a href="https://www.linkedin.com/in/roberto-busby/" class="linkedin-btn" target="_blank">Visit my LinkedIn</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
